id = "cargo-dependencies"
name = "Cargo Dependencies"
description = "Suggestions for cargo dependencies"
version = "0.1.0"
schema_version = 1
authors = ["Frederik <>"]
repository = "https://github.com/zed-industries/zed"

[language_servers.cargo_dependencies]
name = "Cargo Dependencie"
language = "TOML"
languages = ["TOML", "Rust"]
