[package]
name = "toml"
edition.workspace = true
license.workspace = true
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"
git2 = "0.18"
